/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include<stdint.h>

#define RCC  0x40023800
#define GPIOA  0x40020000
#define GPIOC  0x40020800

#define AHB1ENR_RCC ((volatile uint32_t *)(RCC + 0x30))
#define GPIOA_MODER ((volatile uint32_t *)(GPIOA + 0x00))
#define GPIOC_MODER ((volatile uint32_t *)(GPIOC + 0x00))
#define GPIOC_PUPDR ((volatile uint32_t *)(GPIOC + 0x0C))
#define GPIOC_IDR ((volatile uint32_t *)(GPIOC + 0x10))
#define GPIOC_ODR ((volatile uint32_t *)(GPIOC + 0x14))
#define GPIOA_ODR ((volatile uint32_t *)(GPIOA + 0x14))




void GPIO_Init(void);
void Read_Button(void);
void ComparePassword(void);
void ResetPassword(void);
void delay(void);
void delay2(void);
void CorrectPassword(void);
void WrongPassword(void);



void delay(void)
{
    for(volatile uint32_t i = 0; i < 50000; i++);
}

void delay2(void)
{
    for(volatile uint32_t i = 0; i < 300000; i++);
}

/*
1.
Initialization Configure:
PC0, PC1, PC2 as input with internal pull-up
PC3, PC4 as output
PA6 as output
*/
void GPIO_Init(void)
{
    *AHB1ENR_RCC |= (1<<2);
    *AHB1ENR_RCC |= (1<<0);

    //GPIOA_MODER
    *GPIOA_MODER &= ~(0b11 << 12);   // Clear PA6 mode bits
    *GPIOA_MODER |=  (0b01 << 12);   // Set PA6 as General Purpose Output

    //*GPIOC_MODER &= ~(0b11 <<8 ); //Resetting bits clear PC4
    *GPIOC_MODER &= ~(0x3ff << 0 ); //Resetting bits clear PC0 PC1 PC2 PC3

    *GPIOC_MODER |= (1<<8); //set as output
    *GPIOC_MODER |= (1<<6); //set as output

    //GPIOC_PUPDR
    *GPIOC_PUPDR &= ~(0b111111 << 0);   // Resetting bits clear
    *GPIOC_PUPDR |= (0b01 << 0);   // PC0 pull-up
    *GPIOC_PUPDR |= (0b01 << 2);   // PC1 pull-up
    *GPIOC_PUPDR |= (0b01 << 4);   // PC2 pull-up
    //OR *GPIOC_PUPDR |= (0b10101<<0); //PC0, PC1, PC2 as input with internal pull-up

}

/*
2. Password Store a predefined password.
*/

uint8_t buttonIndex = 0;
const uint8_t storedPassword[4] = {1,2,3,1}; // store the password
uint8_t User_Password[4]; //user entered password
uint8_t Matched_Password; //stored how many input mached



/*
5. Compare Password
After receiving 4 button presses
*/


void ComparePassword(void)
{
    Matched_Password = 0;

     for(uint8_t i =0 ; i < 4 ; i++)
    {
    if(storedPassword[i] == User_Password[i])
    {
        Matched_Password++;

    }
    }
    if(Matched_Password == 4)
    {
        CorrectPassword();
    }
    else
    {
        WrongPassword();
    }
}


/*3. Input
Wait until a button is pressed.
If
PC0 pressed → store 1
PC1 pressed → store 2
PC2 pressed → store 3
Store each value in an array.

4. One Press = One Input
If the user keeps holding the button,
Button 1
should be stored only once.
Do not allow
1 1 1 1 1 1
from a single long press.
*/


void Read_Button(void)
{
    uint8_t previous_Switch1 = 1;   // Due to internal pull-up:
    uint8_t previous_Switch2 = 1;   // Switch OFF (Released) -> 1
    uint8_t previous_Switch3 = 1;   // Switch ON (Pressed)   -> 0

    while(1)
    {

     uint8_t Switch1 = (uint8_t)((*GPIOC_IDR >> 0) & 0x01); //Take input from the switches.
     uint8_t Switch2 = (uint8_t)((*GPIOC_IDR >> 1) & 0x01);
     uint8_t Switch3 = (uint8_t)((*GPIOC_IDR >> 2) & 0x01);

        if((previous_Switch1 == 1) && (Switch1 == 0)) //check if the previous switch stage was ON or OFF and apply logical and  operation
        {
            delay();

         if(((*GPIOC_IDR >> 0) & 0x01) == 0)
        {
                if(buttonIndex < 4)
             {
                 User_Password[buttonIndex] = 1; // Store input '1' in the user input password array
                buttonIndex++;
                //(we are not changing the values here as this will keep toggling indefinitly. )
            }
         }
        }

        if((previous_Switch2 == 1) && (Switch2 == 0))
        {
            delay();

         if (((*GPIOC_IDR >> 1) & 0x01)  ==0)
         {
            if(buttonIndex < 4)
             {
                User_Password[buttonIndex] = 2;// Store input '2' in the user input password array
                buttonIndex++;
               }
         }
        }

        if((previous_Switch3 == 1) && (Switch3 == 0))
        {
            delay();

          if (((*GPIOC_IDR >> 2) & 0x01)  ==0)
          {
            if(buttonIndex < 4)
             {
                User_Password[buttonIndex] = 3;// Store input '3' in the user input password array
                buttonIndex++;
            }

           }
        }
        previous_Switch1 = Switch1 ; //store the current stage of the switch
        previous_Switch2 = Switch2;
        previous_Switch3 = Switch3;

      if(buttonIndex == 4)
            {
                ComparePassword();



                ResetPassword();
            }
    }
}


/*6.
Correct Password
If all four values match
Turn ON Green LED.
Turn OFF Red LED.
Turn ON buzzer for 1 second.
Turn OFF Green LED.
Wait for the next attempt.
*/


void CorrectPassword(void)
{
    if(Matched_Password == 4)
    {

		*GPIOC_ODR |= (1<<3); //Turn ON GREEN LED
        *GPIOC_ODR &= ~(1<<4); //Turn OFF RED LED
        *GPIOA_ODR |= (1<<6); //Turn ON Buzzer
        delay2();
        *GPIOA_ODR &= ~(1<<6); //Turn OFF Buzzer
        *GPIOC_ODR &= ~(1<<3); //Turn OFF GREEN LED

    }
}


/*7.
Wrong Password
If even one value is different,
Turn ON Red LED.
Buzzer beeps three times.
Turn OFF Red LED.
Wait for the next attempt.
*/
void WrongPassword(void)
{
    if(Matched_Password != 4)
    {
        *GPIOC_ODR &= ~(1<<3);    // Ensure Green LED is OFF

        for(uint8_t i = 0; i < 3; i++)
        {
            // Turn ON Red LED and Buzzer
            *GPIOC_ODR |= (1<<4);
            *GPIOA_ODR |= (1<<6);
            delay2();

            // Turn OFF Red LED and Buzzer
            *GPIOC_ODR &= ~(1<<4);
            *GPIOA_ODR &= ~(1<<6);
            delay2();
        }
    }
}


/*8.
Reset
Clear the user input array.
Wait for another password entry.
*/

void ResetPassword(void)
{
    for(uint8_t i = 0; i < 4; i++)
    {
        User_Password[i] = 0;
    }

    buttonIndex = 0;
}




int main(void)
{
    GPIO_Init();      // Configure GPIO pins

    Read_Button();    // Start reading buttons

    while(1)
    {

    }
}

