/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

	void delay()
	{
		for(volatile uint32_t i=0 ; i<300000 ; i++);
	}

int main(void)
{
	volatile uint32_t *GPIOC_MODER = (uint32_t*) (0x40020800 +  0x00);
	volatile uint32_t *GPIOC_ODR = (uint32_t*) (0x40020800 +  0x14); //output
	volatile uint32_t *GPIOC_IDR = (uint32_t*) (0x40020800 +  0x10);   //input
	volatile uint32_t *AHB1_RCC_GPIOCEN = (uint32_t*) (0x40023800 + 0x30);  //(1<<2);

	*AHB1_RCC_GPIOCEN |= (1<<2); // ENABLE GPIOC

	*GPIOC_MODER &= ~(3 << 0);
	*GPIOC_MODER |= (1<<2); // set 01: General purpose output mode

	// *GPIOC_MODER = (0x00<<0); // set 00: Input GPIOC is in input mode by default


	while(1){
	uint8_t value;
	value = (uint8_t)((*GPIOC_IDR >> 0) & 0x01);
	if(value == 0 )
	{
		delay();
		*GPIOC_ODR ^=(1<<1);
	}

	}
}
