/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC   0x40023800
#define GPIOA 0x40020000
#define ADC1  0x40012000
#define USART2  0x40004400

#define RCC_AHB1ENR   ((volatile uint32_t *)(RCC   + 0x30))
#define RCC_APB2ENR   ((volatile uint32_t *)(RCC   + 0x44))

#define RCC_APB1ENR   ((volatile uint32_t *)(RCC   + 0x40)) //For USART2


#define GPIOA_MODER ((volatile uint32_t *)(GPIOA + 0x00))
#define GPIOA_AFRL  ((volatile uint32_t *)(GPIOA + 0x20)) //FOR USART2
#define GPIOA_ODR ((volatile uint32_t *)(GPIOA + 0x14))

#define ADC_CR1     ((volatile uint32_t *)(ADC1 + 0x04))
#define ADC_CR2     ((volatile uint32_t *)(ADC1 + 0x08))
#define ADC_SMPR2   ((volatile uint32_t *)(ADC1 + 0x10))
#define ADC_SQR1    ((volatile uint32_t *)(ADC1 + 0x2C))
#define ADC_SQR3    ((volatile uint32_t *)(ADC1 + 0x34))
#define ADC_SR      ((volatile uint32_t *)(ADC1 + 0x00))
#define ADC_DR      ((volatile uint32_t *)(ADC1 + 0x4C))
#define ADC_CCR     ((volatile uint32_t *)((ADC1 + 0x300) + 0x04 ))

#define USART2_CR1     ((volatile uint32_t *)(USART2 + 0x0C))
#define USART2_SR      ((volatile uint32_t *)(USART2 + 0x00))
#define USART2_DR      ((volatile uint32_t *)(USART2 + 0x04))
#define USART2_BRR     ((volatile uint32_t *)(USART2 + 0x08))

void GPIO_Init(void);
void ADC_Init(void);
uint16_t ADC_Read(void);
void USART2_INIT(void);
void USART2_SendChar(char data);
void ASCII_conversion(uint16_t ADC_value);
void delay(void);
void LED_Control(uint16_t ADC_value);



void GPIO_Init(void)
{
    *RCC_AHB1ENR |= (1 << 0);

    *GPIOA_MODER &= ~(0b11 << 0);
    *GPIOA_MODER |=  (0b11 << 0);

    *GPIOA_MODER &= ~(0b11 << 10);
     *GPIOA_MODER |=  (0b01 << 10);

}


void delay(void)
{
    for (volatile uint32_t i = 0; i < 500000; i++)
    {
    }
}





void USART2_INIT(void)
{
    *RCC_APB1ENR |= (1 << 17);

    *GPIOA_MODER &= ~(0b11 << 4);
    *GPIOA_MODER |=  (0b10 << 4);

    *GPIOA_AFRL &= ~(0b1111 << 8);
    *GPIOA_AFRL |=  (0b0111 << 8);

    *USART2_CR1 &= ~(0b1 << 15);

    *USART2_BRR &= ~((0XFFF << 4) | (0b1111 << 0));
    *USART2_BRR |=  ((8 << 4) | (11 << 0));


    *USART2_CR1  &= ~((0b1 << 3) | (0b1 << 13));
    *USART2_CR1  |=  (0b1 << 3);
    *USART2_CR1 |=  (0b1 << 13);

}



void LED_Control(uint16_t ADC_value)
{



    if(ADC_value < 2000)
    {
        *GPIOA_ODR |= (1 << 5);
    }
    else
    {
        *GPIOA_ODR &= ~(1 << 5);
    }

}


void USART2_SendChar(char data)
{
  while ((( *USART2_SR >> 7 ) & 1) == 0)
   {

   }
  *USART2_DR = data;

}

void ADC_Init(void)
{
    *RCC_APB2ENR |= (1 << 8);
    *ADC_CR1     &= ~(0b11 << 24);
    *ADC_SMPR2   &= ~(0b111 << 0);
    *ADC_SMPR2   |=  (0b100 << 0);
    *ADC_SQR1    &= ~(0b1111 << 20);
    *ADC_SQR1    |=  (0b0000 << 20);
    *ADC_SQR3    &= ~(0b11111 << 0);
    *ADC_SQR3    |=  (0b00000 << 0);

    *ADC_CR2 &= ~((0b1 << 0)|
                (0b1 << 1)  |
                (0b1 << 30) |
                (0b1 << 11) |
                (0b1 << 10) |
                (0b11 << 28)|
                (0b1 << 8)  |
                (0b1 << 9));

    *ADC_CR2 |=  ((0b1 << 0)|
                (0b0 << 1)  |
                (0b0 << 11) |
                (0b0 << 10) |
                (0b00 << 28));

    *ADC_CCR &= ~(0b11 << 16);
    *ADC_CCR |=  (0b11 << 16);

}

uint16_t ADC_Read(void)
{
    *ADC_CR2 |=(0b1 << 30);

    while ((*ADC_SR >> 1) == 0)
    {

    }
    return (*ADC_DR);
}

void ASCII_conversion(uint16_t ADC_value)
{
    uint16_t Thousands;
    uint16_t Hundreds;
    uint16_t Tens;
    uint16_t Ones;

    Thousands = ADC_value / 1000;
    Hundreds  = (ADC_value / 100) % 10;
    Tens      = (ADC_value / 10) % 10;
    Ones      = ADC_value % 10;

    USART2_SendChar(Thousands + '0');
    USART2_SendChar(Hundreds + '0');
    USART2_SendChar(Tens + '0');
    USART2_SendChar(Ones + '0');
}

int main()
{
    GPIO_Init();
    ADC_Init();
    USART2_INIT();



    while (1)
       {

    	uint16_t ADC_value = ADC_Read();

           ASCII_conversion(ADC_value);

           USART2_SendChar('\r');
           USART2_SendChar('\n');

           delay();

           LED_Control(ADC_value);
       }
    return 0;
}
