/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>

#define RCC   0x40023800
#define GPIOA 0x40020000
#define TIM2 0x40000000

#define AHB1ENR     ((volatile uint32_t *)(RCC + 0x30))
#define APB1ENR     ((volatile uint32_t *)(RCC +  0x40))

#define GPIOA_MODER ((volatile uint32_t *)(GPIOA + 0x00))
#define GPIOA_PUPDR ((volatile uint32_t *)(GPIOA + 0x0C))
#define GPIOA_IDR   ((volatile uint32_t *)(GPIOA + 0x10))
#define GPIOA_AFRL   ((volatile uint32_t *)(GPIOA + 0x20))

#define TIM2_CR1     ((volatile uint32_t *)(TIM2 + 0x00))
#define TIM2_EGR     ((volatile uint32_t *)(TIM2 + 0x14))
#define TIM2_CCMR1   ((volatile uint32_t *)(TIM2 + 0x18))
#define TIM2_CCER    ((volatile uint32_t *)(TIM2 + 0x20))
#define TIM2_CCR2    ((volatile uint32_t *)(TIM2 + 0x38))

#define TIM2_CNT     ((volatile uint32_t *)(TIM2 + 0x24))
#define TIM2_PSC     ((volatile uint32_t *)(TIM2 + 0x28))
#define TIM2_ARR     ((volatile uint32_t *)(TIM2 + 0x2C))



void GPIO_Init(void);
void TIM2_Init(void);
void Switch_Read(void);
uint8_t Switch_Debounce(volatile uint32_t *IDR, uint32_t pin);
void Delay(volatile uint32_t count);
uint8_t last_button_state =1;
uint8_t current_button_state ,pos =0, new_press;



void Delay(volatile uint32_t count)
{
    for (volatile uint32_t i = 0; i < count; i++)
    {

    }
}




void GPIO_Init(void)
{
*AHB1ENR &= ~(1 << 0 );
*AHB1ENR |=  (1 << 0 );

*GPIOA_MODER &= ~(0b11 << 8 );

*GPIOA_MODER &= ~(0b11 << 2 );
*GPIOA_MODER |=  (0b10 << 2 );

*GPIOA_PUPDR &= ~(0b11 << 8 );
*GPIOA_PUPDR |=  (0b01 << 8 );

*GPIOA_AFRL  &= ~(0b1111 << 4 );
*GPIOA_AFRL  |=  (0b0001 << 4 );
}

void TIM2_Init(void)
{
    *APB1ENR |= (1 << 0);

    *TIM2_CCMR1 &= ~((1 << 11) | (0b111 << 12));
    *TIM2_CCMR1 |=  ((1 << 11) | (0b110 << 12));

   *TIM2_CCER &= ~(1 << 4);
   *TIM2_CCER |=  (1 << 4);

    *TIM2_PSC =   15;
    *TIM2_ARR =   19999;
    *TIM2_CCR2 = 1500;

   *TIM2_EGR |=  (1 << 0);
    *TIM2_CR1    |= (1 << 0);
}


void Switch_Read(void)
{

    current_button_state =(Switch_Debounce(GPIOA_IDR, 4));
    new_press = 0 ;

    if (last_button_state == 1 && current_button_state == 0 )
    {
        new_press = 1;
    }
    else
    {
        new_press = 0;
    }
    last_button_state = current_button_state;

    if(new_press == 1)

    {

    pos++;

    if(pos == 1)
    {
        *TIM2_CCR2 = 1000;
    }
    if(pos == 2)
    {
        *TIM2_CCR2 = 1500;
    }
    if(pos == 3)
    {
        *TIM2_CCR2 = 2000;
        pos = 0;
    }
}
}


uint8_t Switch_Debounce(volatile uint32_t *IDR, uint32_t pin)
{
    if (!(*IDR & (1 << pin)))
    {
        Delay(10000);

        if (!(*IDR & (1 << pin)))
        {
            return 0;
        }
    }

    return 1;
}




int main(void)
{
    GPIO_Init();
    TIM2_Init();


    while (1)
    {
        Switch_Read();

    }
}
