/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdint.h>

#define RCC 0x40023800
#define GPIOC 0x40020800
#define TIM2 0x40000000

#define RCC_AHB1ENR   ((volatile uint32_t *)(RCC   + 0x30))
#define RCC_APB1ENR   ((volatile uint32_t *)(RCC   + 0x40))
#define GPIOC_MODER   ((volatile uint32_t *)(GPIOC + 0x00))
#define GPIOC_PUPDR ((volatile uint32_t *)(GPIOC   + 0x0C))
#define GPIOC_ODR     ((volatile uint32_t *)(GPIOC + 0x14))


#define TIM2_CR1      ((volatile uint32_t *)(TIM2 + 0x00))
#define TIM2_DIER     ((volatile uint32_t *)(TIM2 + 0x0C))
#define TIM2_SR       ((volatile uint32_t *)(TIM2 + 0x10))
#define TIM2_EGR      ((volatile uint32_t *)(TIM2 + 0x14))
#define TIM2_CNT      ((volatile uint32_t *)(TIM2 + 0x24))
#define TIM2_PSC      ((volatile uint32_t *)(TIM2 + 0x28))
#define TIM2_ARR      ((volatile uint32_t *)(TIM2 + 0x2C))

#define NVIC_ISER0    ((volatile uint32_t *)(0xE000E100))
#define TIMER_PRESCALER 15999
#define TIMER_PERIOD     999

void GPIO_Init(void);
void TIM2_Init(void);
void TIM2_IRQHandler(void);

void GPIO_Init(void)
{
    *RCC_AHB1ENR |= (1 << 2);

    *GPIOC_MODER &= ~(  //Resetting PC0, PC3 and PC4
    (0b11 << 0) |
    (0b11 << 6) |
    (0b11 << 8)
    );

    *GPIOC_MODER |=
     (0b00 << 0) |
     (0b01 << 6) |
     (0b01 << 8); //SET PC0 as Input, PC3 and PC4 as Output

    *GPIOC_PUPDR &= ~(0b11 << 0);   // Configure PC0 as input with internal pull-up
    *GPIOC_PUPDR |= (0b01  << 0);

}

void TIM2_Init(void)
{
    // Enable TIM2 peripheral clock
    *RCC_APB1ENR |= (1 << 0);

    // Configure timer period
    *TIM2_PSC     = TIMER_PRESCALER;
    *TIM2_ARR     = TIMER_PERIOD;


    // Load PSC/ARR into active registers
    *TIM2_EGR    |= (1 << 0);

    // Clear pending update flag
    *TIM2_SR     &= ~(1 << 0);

    // Enable update interrupt
    *TIM2_DIER   |= (1 << 0);

    // Enable TIM2 interrupt (IRQ28) in NVIC
    *NVIC_ISER0  |= (1<<28);

    // Start timer
    *TIM2_CR1    |= (1 << 0);
}

void TIM2_IRQHandler(void) // Handle the interrupt
{

    *TIM2_SR     &= ~(1 << 0);// Clear Update Interrupt Flag (UIF)

	*GPIOC_ODR   ^=  (1 << 3);// Toggle Green LED connected to PC3

    // 3. Return (this happens automatically when the function ends)
}


int main(void)
{
    GPIO_Init();

    TIM2_Init();

    while(1)
    {

    }
}
