/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC  0x40023800
#define GPIOC  0x40020800
#define EXTI  0x40013C00
#define SYSCFG  0x40013800

#define AHB1ENR_RCC ((volatile uint32_t *)(RCC + 0x30))
#define APB2ENR_RCC ((volatile uint32_t *)(RCC + 0x44))

#define GPIOC_MODER ((volatile uint32_t *)(GPIOC + 0x00))
#define GPIOC_PUPDR ((volatile uint32_t *)(GPIOC + 0x0C))
#define GPIOC_IDR ((volatile uint32_t *)(GPIOC + 0x10))
#define GPIOC_ODR ((volatile uint32_t *)(GPIOC + 0x14))

#define SYSCFG_EXTICR1 ((volatile uint32_t *)(SYSCFG + 0x08))

#define EXTI_IMR ((volatile uint32_t *)(EXTI +  0x00))
#define EXTI_RTSR ((volatile uint32_t *)(EXTI + 0x08))
#define EXTI_FTSR ((volatile uint32_t *)(EXTI + 0x0C))
#define EXTI_PR ((volatile uint32_t *)(EXTI + 0x14))

#define NVIC_ISER0 ((volatile uint32_t *)(0xE000E100))



void GPIO_Init(void);
void EXTI_Config(void);
void NVIC_Config(void);
void EXTI0_IRQHandler(void);



void GPIO_Init(void)
{
    *AHB1ENR_RCC |= (1<<2);


    *GPIOC_MODER &= ~(0b11 << 0 ); //Resetting bits clear PC0 and set as input
   // *GPIOC_MODER |= (0b00<<0); //set as input

    *GPIOC_MODER &= ~(0b11 << 6 ); //Resetting bits clear PC3
    *GPIOC_MODER |= (0b01<<6); //set as output

    //GPIOC_PUPDR
    *GPIOC_PUPDR &= ~(0b11 << 0);   // Resetting bits clear
    *GPIOC_PUPDR |= (0b01 << 0);   // PC0 pull-up


}

void EXTI_Config(void)
{
	*APB2ENR_RCC |= (1 << 14); //Enable the SYSCFG clock.


	*SYSCFG_EXTICR1 &= ~(0xf << 0);   // Clear line 0 port bits
	*SYSCFG_EXTICR1 |= (0b0010 << 0);  // Set EXTI0 to GPIOC

	*EXTI_IMR  |= (1 << 0);    // Unmask EXTI line 0
	*EXTI_FTSR |= (1 << 0);    // Enable falling edge trigger
	*EXTI_RTSR &= ~(1 << 0);    // Disable rising edge trigger

}

void NVIC_Config(void)
{
	*NVIC_ISER0 |= (1<<6);   // Enable IRQ6 (EXTI0) in NVIC {from vector table}
}


void EXTI0_IRQHandler(void) // Handle the interrupt
{
	// 1. Clear the pending interrupt flag
	*EXTI_PR = (1 << 0);

	 // 2.  Toggle PC3 (LED)
	*GPIOC_ODR ^= (1 << 3);

    // 3. Return (this happens automatically when the function ends)
}


int main(void)
{
	  GPIO_Init();      // Configure GPIO pins
	  EXTI_Config();	 // Configure EXTI0 button interrupt
	  NVIC_Config();	// Enable interrupt in NVIC
	  while(1)
	  {
		  //  wait for interrupt

	  }
}
